#!/bin/bash
# vim:set noexpandtab:

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions	# Loads the generic functions usually used in the script
source /usr/share/yunohost/helpers # Source app helpers

CLEAN_SETUP () {
	# Clean installation residues that are not supported by the remove script.
	# Clean hosts
	echo ""
}
TRAP_ON	# Active trap to stop the script if an error is detected.

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

script_dir=$PWD

# Check variables are not empty
CHECK_VAR "$app" "app name not set"
CHECK_VAR "$script_dir" "script_dir not set"

CHECK_PATH	# Check and fix path syntax
CHECK_DOMAINPATH	# Check and fix domain disponibility

CHECK_FINALPATH	# Check final path

# Check domain with regex
domain_regex=$(echo "$domain" | sed 's@-@.@g')
CHECK_VAR "$domain_regex" "domain_regex empty"

# Save app settings
ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app is_public $is_public

# Copy files to the right place
final_path=/var/www/$app
sudo git clone https://framagit.org/framasoft/framaestro.git $final_path
ynh_app_setting_set $app final_path $final_path

# Copy it to Nginx conf directory
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Change variables in nginx configuration
if [ $is_public -eq 1 ];
then
	sudo sed -i "s@#--PRIVATE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
fi
sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf

## Copy config
sudo cp ../conf/config.js "${final_path}/p/config.js"


# Make app public or private
if [ $is_public -eq 0 ];
then	# If the app is private, only the shortened URLs are publics
	ynh_app_setting_set $app protected_uris "/"
else
	ynh_app_setting_set $app skipped_uris "/"
fi

# Set right permissions on new files created at first start
sudo chown -R www-data: "$final_path"

if [ $is_public -eq 0 ];
then
	# Delete public access
	ynh_app_setting_delete $app unprotected_uris
	# Regenerate SSOwat's configuration
	sudo yunohost app ssowatconf
fi

# Reload Nginx
sudo service nginx reload
