#!/bin/bash
# vim:set noexpandtab:

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Loads the generic functions usually used in the script
source /usr/share/yunohost/helpers # Source app helpers

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)

SECURE_REMOVE '/var/www/$app'	# Delete directory application

REMOVE_NGINX_CONF	# Delete nginx configuration

# Reload SSOwat configuration
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
